import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('zh'), Locale('en'), Locale('ja')];
  static const delegate = _AppLocalizationsDelegate();

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  String t(String key) =>
      (_values[locale.languageCode] ?? _values['zh']!)[key] ??
      _values['zh']![key] ??
      key;

  static const _values = <String, Map<String, String>>{
    'zh': {
      'discover': '发现',
      'timeline': '时间线',
      'browse': '浏览',
      'rakuen': '超展开',
      'profile': '我的',
      'toggleTheme': '切换主题',
      'profileSubtitle': '收藏、进度与客户端设置',
      'guestMode': '访客模式',
      'loginSync': '登录后同步收藏与观看进度',
      'login': '登录',
      'logout': '退出登录',
      'logoutMessage': '将清除本机保存的登录会话。',
      'cancel': '取消',
      'logoutAction': '退出',
      'collections': '收藏',
      'people': '人物',
      'friends': '好友',
      'shortcuts': '快捷入口',
      'myCollections': '我的收藏',
      'characterCollections': '人物收藏',
      'myBlogs': '我的日志',
      'myIndexes': '我的目录',
      'myFriends': '我的好友',
      'myTimeline': '我的时间线',
      'myStats': '我的统计',
      'account': '账户',
      'accountProfile': '账户资料',
      'loginToManage': '登录后管理账户',
      'privacy': '隐私与可见性',
      'privacySubtitle': '收藏隐私可在编辑收藏时单独设置',
      'privacyHint': '当前支持逐条收藏设置公开范围',
      'displayPerformance': '显示与性能',
      'appearance': '外观',
      'darkTheme': '深色主题',
      'lightTheme': '浅色主题',
      'language': '语言',
      'languageSubtitle': '中文、English、日本語',
      'appIcon': '应用图标',
      'classicIcon': '传统图标',
      'animeIcon': '二次元图标',
      'iconAndroidHint': 'Android 启动器图标会随选择更新',
      'iconDesktopHint': 'Windows 窗口与任务栏图标会随选择更新',
      'screenRefresh': '屏幕刷新率',
      'screenRefreshSubtitle': '跟随系统，支持最高 120Hz',
      'autoPlay': '自动播放预览',
      'reduceMotion': '减少界面动效',
      'reduceMotionSubtitle': '适合省电模式或低性能设备',
      'notifications': '通知',
      'updateReminder': '更新提醒',
      'updateReminderSubtitle': '保留本机提醒偏好',
      'dataNetwork': '数据与网络',
      'clearCache': '清除图片缓存',
      'clearCacheSubtitle': '释放封面、头像与预览图片占用',
      'cacheCleared': '图片缓存已清除',
      'networkDiagnostics': '网络诊断',
      'networkDiagnosticsSubtitle': '测试 next.bgm.tv API 连接',
      'connecting': '正在连接 Bangumi…',
      'connectionOk': '连接正常，可以访问 Bangumi',
      'connectionFailed': '连接失败',
      'about': '关于',
      'version': '版本',
      'loading': '读取中',
      'checkUpdate': '检查更新',
      'checkUpdateSubtitle': '从 GitHub Releases 获取最新版本',
      'latestVersion': '当前已是最新版',
      'newVersion': '发现新版本',
      'currentVersion': '当前版本',
      'newestVersion': '最新版本',
      'later': '稍后',
      'openRelease': '查看发布页',
      'updateFailed': '检查更新失败',
      'dataSource': '数据来源',
    },
    'en': {
      'discover': 'Discover',
      'timeline': 'Timeline',
      'browse': 'Browse',
      'rakuen': 'Community',
      'profile': 'Me',
      'toggleTheme': 'Toggle theme',
      'profileSubtitle': 'Collections, progress, and app settings',
      'guestMode': 'Guest mode',
      'loginSync': 'Sign in to sync collections and progress',
      'login': 'Sign in',
      'logout': 'Sign out',
      'logoutMessage': 'This will remove the saved session from this device.',
      'cancel': 'Cancel',
      'logoutAction': 'Sign out',
      'collections': 'Collections',
      'people': 'People',
      'friends': 'Friends',
      'shortcuts': 'Shortcuts',
      'myCollections': 'My collections',
      'characterCollections': 'Character collections',
      'myBlogs': 'My blogs',
      'myIndexes': 'My indexes',
      'myFriends': 'My friends',
      'myTimeline': 'My timeline',
      'myStats': 'My statistics',
      'account': 'Account',
      'accountProfile': 'Account profile',
      'loginToManage': 'Sign in to manage your account',
      'privacy': 'Privacy and visibility',
      'privacySubtitle': 'Set visibility separately when editing a collection',
      'privacyHint': 'Collection visibility can currently be set per item',
      'displayPerformance': 'Display and performance',
      'appearance': 'Appearance',
      'darkTheme': 'Dark theme',
      'lightTheme': 'Light theme',
      'language': 'Language',
      'languageSubtitle': '中文、English、日本語',
      'appIcon': 'App icon',
      'classicIcon': 'Classic icon',
      'animeIcon': 'Anime icon',
      'iconAndroidHint': 'The Android launcher icon updates with your choice',
      'iconDesktopHint': 'The Windows title bar and taskbar icon will update',
      'screenRefresh': 'Display refresh rate',
      'screenRefreshSubtitle': 'Follows the system, up to 120 Hz',
      'autoPlay': 'Autoplay previews',
      'reduceMotion': 'Reduce motion',
      'reduceMotionSubtitle': 'Useful for battery saver or slower devices',
      'notifications': 'Notifications',
      'updateReminder': 'Update reminders',
      'updateReminderSubtitle': 'Keep notification preference on this device',
      'dataNetwork': 'Data and network',
      'clearCache': 'Clear image cache',
      'clearCacheSubtitle': 'Free space used by covers, avatars, and previews',
      'cacheCleared': 'Image cache cleared',
      'networkDiagnostics': 'Network diagnostics',
      'networkDiagnosticsSubtitle': 'Test the next.bgm.tv API connection',
      'connecting': 'Connecting to Bangumi…',
      'connectionOk': 'Bangumi is reachable',
      'connectionFailed': 'Connection failed',
      'about': 'About',
      'version': 'Version',
      'loading': 'Loading',
      'checkUpdate': 'Check for updates',
      'checkUpdateSubtitle': 'Get the latest version from GitHub Releases',
      'latestVersion': 'You are using the latest version',
      'newVersion': 'Update available',
      'currentVersion': 'Current version',
      'newestVersion': 'Latest version',
      'later': 'Later',
      'openRelease': 'Open release page',
      'updateFailed': 'Update check failed',
      'dataSource': 'Data source',
    },
    'ja': {
      'discover': 'ホーム',
      'timeline': 'タイムライン',
      'browse': '探す',
      'rakuen': 'コミュニティ',
      'profile': 'マイページ',
      'toggleTheme': 'テーマを切り替え',
      'profileSubtitle': 'コレクション、進捗、アプリ設定',
      'guestMode': 'ゲストモード',
      'loginSync': 'ログインしてコレクションと進捗を同期',
      'login': 'ログイン',
      'logout': 'ログアウト',
      'logoutMessage': 'この端末に保存されたセッションを削除します。',
      'cancel': 'キャンセル',
      'logoutAction': 'ログアウト',
      'collections': 'コレクション',
      'people': '人物',
      'friends': '友だち',
      'shortcuts': 'ショートカット',
      'myCollections': 'マイコレクション',
      'characterCollections': 'キャラクターコレクション',
      'myBlogs': 'マイブログ',
      'myIndexes': 'マイ目録',
      'myFriends': '友だち',
      'myTimeline': 'マイタイムライン',
      'myStats': 'マイ統計',
      'account': 'アカウント',
      'accountProfile': 'アカウント情報',
      'loginToManage': 'ログインしてアカウントを管理',
      'privacy': 'プライバシーと公開範囲',
      'privacySubtitle': 'コレクション編集時に公開範囲を設定できます',
      'privacyHint': '項目ごとに公開範囲を設定できます',
      'displayPerformance': '表示とパフォーマンス',
      'appearance': '外観',
      'darkTheme': 'ダークテーマ',
      'lightTheme': 'ライトテーマ',
      'language': '言語',
      'languageSubtitle': '中文、English、日本語',
      'appIcon': 'アプリアイコン',
      'classicIcon': '従来のアイコン',
      'animeIcon': 'アニメアイコン',
      'iconAndroidHint': 'Android のランチャーアイコンも切り替わります',
      'iconDesktopHint': 'Windows のウィンドウとタスクバーに反映されます',
      'screenRefresh': '画面のリフレッシュレート',
      'screenRefreshSubtitle': 'システムに従い、最大 120Hz に対応',
      'autoPlay': 'プレビューを自動再生',
      'reduceMotion': 'アニメーションを減らす',
      'reduceMotionSubtitle': '省電力モードや低性能端末向け',
      'notifications': '通知',
      'updateReminder': 'アップデート通知',
      'updateReminderSubtitle': 'この端末に通知設定を保存',
      'dataNetwork': 'データとネットワーク',
      'clearCache': '画像キャッシュを削除',
      'clearCacheSubtitle': '表紙、アバター、プレビューの容量を解放',
      'cacheCleared': '画像キャッシュを削除しました',
      'networkDiagnostics': 'ネットワーク診断',
      'networkDiagnosticsSubtitle': 'next.bgm.tv API への接続をテスト',
      'connecting': 'Bangumi に接続中…',
      'connectionOk': 'Bangumi に接続できます',
      'connectionFailed': '接続に失敗しました',
      'about': 'このアプリについて',
      'version': 'バージョン',
      'loading': '読み込み中',
      'checkUpdate': 'アップデートを確認',
      'checkUpdateSubtitle': 'GitHub Releases から最新版を確認',
      'latestVersion': '最新版を使用しています',
      'newVersion': '新しいバージョンがあります',
      'currentVersion': '現在のバージョン',
      'newestVersion': '最新バージョン',
      'later': 'あとで',
      'openRelease': 'リリースページを開く',
      'updateFailed': 'アップデート確認に失敗しました',
      'dataSource': 'データ提供元',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
